demo/example_index.html
Otherwise demo code does not work
=> Comment out persistence when initialising

README.md, client/js/app/utils/ExplorerUtils.js, client/js/app/utils/ProjectUtils.js, demo/example_index.html, dist/keen-data-tools.js, test/support/TestHelpers.js, test/unit/utils/ProjectUtilsSpec.js
Removes the master key requirement
@hex337 @dustinlarimer @aroc I'm gonna go ahead and merge this on the public version, for the sake of time. Any changes from private review can be moved back over.
=> Remove master key

client/js/app/modules/persistence/persistence.js, dist/keen-data-tools.js, gulpfile.js, package.json, test/unit/modules/persistence/rest_spec.js
Fixes the file naming issues with `rest.js`. I also fixed some selenium dependencies, cause they were bugging me (although we don't seem to actually have any functional tests yet)
closes #14
=> fix some dependency issues and lowercase all references to rest.js

client/js/app/modules/persistence/persistence.js, dist/keen-data-tools.js
Fixes the repo to work according to the checkout instructions (see #25)
The fix is pretty simple; I also included the changes to the dist, not sure if that's what you want though
Follow the instructions in the README - before the PR, it fails, after the PR, it works
=> fix dependency #25

README.md
Talked to @josephwegner about making this change, feel free to correct me if I misunderstood anything
* open source version is now the version on keen.io, updated README.md to reflect that
* removed stuff about having a private fork then syncing this open source version, since no longer true
By checking my words
N/A
No
N/A
=> Removed copy about private first, then sync OS

.gitignore, .npmignore, bower.json, package.json
* Create and populate `.npmignore` file
* Create and populate `bower.json` file
* Update `.gitignore` and `package.json` files
=> Prepare for npm/bower publish

client/js/app/components/explorer/visualization/keen_viz.js
Hi,
this simple bugfix adjusts the size of the table chart in the chart area.
Are you interested?
=> Chart width 100%

client/js/app/stores/ExplorerStore.js, client/js/app/utils/ExplorerUtils.js, client/js/app/utils/FunnelUtils.js, dist/keen-explorer.css
A few init fixes here for loading funnels in at app initialization.
@aroc there is an issue here regarding nested forms in the funnel builder... 
`Uncaught Error: Invariant Violation: findComponentRoot(..., .0.1.0.0.1.0.2.1.$0.0.1.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID `
=> a few fixes for loading in funnel steps on init

client/js/app/components/explorer/query_builder/funnels/funnel_step.js
This fixes the issue where clicking the step move buttons would also call the toggleStepActive function.
=> Funnels UI: Step event handling

CONTRIBUTING.md, README.md
Updates CONTRUTING.md and README.md files with new template for Pull Requests.
=> Add CONTRIBUTING.md and README.md update

client/js/app/components/explorer/index.js, client/js/app/components/explorer/query_actions.js, client/js/app/components/explorer/visualization/index.js, client/js/app/components/explorer/visualization/keen_viz_config.js, client/js/app/stores/AppStateStore.js, dist/keen-explorer.css, test/support/TestHelpers.js, test/unit/components/explorer/query_actions_spec.js, test/unit/components/explorer/visualization/keen_viz_config_spec.js, test/unit/index.js
This is the starting point for the new dataviz config component. This may not be the final resting place for the component; it was selected for ease of initial development. It's quite possible that it may be moved within the project or completely externalized at a later date.
This PR actually doesn't *do* anything, it's just scaffolding for other work.
Additionally, a redundant `filters` property was removed from a model in `TestHelpers.js`.
A single test was provided to ensure the component builds, but as mentioned above, the component doesn't do anything yet, and there's not much else to test.
Fetch the branch and/or deploy to staging to test the following:
- (N/A) Does the UI, pixel by pixel, look exactly as expected (check various screen sizes, including mobile)?
- (N/A) If the …
=> Create dataviz config comp

client/js/app/components/explorer/index.js, client/js/app/utils/ExplorerUtils.js, client/js/app/utils/FormatUtils.js, client/js/vendor/picker.date.js, client/js/vendor/picker.js, client/js/vendor/picker.time.js, client/styles/base.less, gulpfile.js, package.json, webpack.config.js
This PR replaces some of our gulp build steps with webpack and adds npm scripts for our common gulp tasks. We're switching to webpack to standardize and simplify our build process for our JS projects.
This PR also updates pickadate (because the version we used was incompatible with webpack), and fixes some accidental global variables in our codebase.
* Run `npm install`. There are quite a few new modules.
* Run
* `npm run dev`
* `npm run build`
* `npm run minify`
* `npm run production`
and make sure they work correctly.
=> Use webpack instead of gulp

README.md
This PR updates the installation instructions for getting the latest version of this app up and running.
=> Update README with latest files and install interface

lib/js/app/components/explorer/Timeframe.js, package-lock.json
when you change the date in Absolute Timeframe, the time is by default set to 12:00 (12 pm)
this fix set this time to 00:00 (12 am)
=> set picker time to midnight instead of midday

README.md, lib/css/components/dataviz.css, lib/js/app/components/App.js, lib/js/app/components/explorer/Dataviz.js, lib/js/app/components/explorer/Filters.js, lib/js/app/components/explorer/Timeframe.js, lib/js/app/redux/reducers/ui.js, lib/js/app/utils/ChartTypes.js, package-lock.json, package.json, test/demo/keen-explorer.css
- options for customization UI
- fix exctactions error and allow to save it(#296, #294)
- fix for chart points color
- possibility to manually modify time range (#292)
=> dlacheta bugs fix

lib/js/app/components/App.js
fix for https://github.com/keen/explorer/issues/304
=> fix typo for savedQueryBrowser

.circleci/config.yml, lib/js/app/components/App.js, lib/js/app/components/explorer/Percentile.js, lib/js/app/components/explorer/SavedQuery.js, lib/js/app/components/explorer/SelectTargetProperty.js, lib/js/index.js, package-lock.json, package.json
Fix issue with query saving
Closes: #306
=> fix: 🐛 query save

lib/js/app/components/App.js, lib/js/app/components/explorer/EventCollection.js
https://github.com/keen/keen/issues/35
=> fix: 🐛 fix for persisted query parameters

test/demo/index.html
index.html is required to start the app
=> chore: 🤖 restore missing index.html file

lib/js/app/components/explorer/Dataviz.js, test/demo/keen-explorer.css
sortedGroups overwrites asc/desc params
https://github.com/keen/keen/issues/48
=> fix: 🐛 remove sortedGroups param

lib/js/app/components/explorer/EmbedHTML.js
add chart type to embed code feature
=> fix: 🐛 embed code

lib/js/app/components/explorer/SavedQueryBrowser.js
https://metakeen.atlassian.net/browse/FRON-36
=> fix: 🐛 change date to user_last_modified_date

lib/js/app/utils/filter.js
https://metakeen.atlassian.net/browse/FRON-48
=> fix: 🐛 issue with parsing filters value

lib/js/app/components/App.tsx, lib/js/app/components/CacheQuery/CacheQuery.tsx, lib/js/app/components/explorer/Timeframe.tsx, lib/js/app/redux/actionCreators/ui.js, lib/js/app/utils/filter.js, lib/js/app/utils/filter.test.js
https://metakeen.atlassian.net/browse/FRON-166
=> refactor: 💡 timezone support in timeframes

lib/js/app/queryCreator/components/RelativeTime/text.json, lib/js/app/queryCreator/components/TimePeriod/TimePeriod.tsx
https://metakeen.atlassian.net/browse/FEE-37
=> refactor: 💡 label update and minValue set for timeframe

lib/js/app/queryCreator/components/Analysis/constants.ts
https://metakeen.atlassian.net/browse/FEE-76
=> chore: 🤖 update copies for analysis

lib/js/app/components/BrowserQueryMenu/BrowserQueryMenu.test.tsx, lib/js/app/components/BrowserQueryMenu/BrowserQueryMenu.tsx
https://metakeen.atlassian.net/browse/FEE-60
=> test: 💍 add tests for <BrowserQueryMenu />

lib/js/app/components/ActionsMenu/ActionsMenu.test.tsx, lib/js/app/components/ActionsMenu/ActionsMenu.tsx, lib/js/app/components/ActionsMenu/text.json, lib/js/app/components/BrowserQueryMenu/BrowserQueryMenu.tsx, lib/js/app/components/EditorNavigation/EditorNavigation.tsx, lib/js/app/modules/app/saga.ts, lib/js/app/modules/app/text.json
* update text copies
* enable to hide menu
=> refactor: 💡 update text and add onHideMenu

package.json, yarn.lock
https://metakeen.atlassian.net/browse/FEE-148
=> fix: 🐛 bump ui-core to fix squashed cells in table

lib/js/app/components/DataViz/DataViz.styles.ts
https://metakeen.atlassian.net/browse/FEE-158
=> fix: 🐛 overflow table

lib/js/app/queryCreator/components/Interval/constants.ts, lib/js/app/queryCreator/components/RelativeTime/RelativeTime.test.tsx, lib/js/app/queryCreator/components/RelativeTime/RelativeTime.tsx, lib/js/app/queryCreator/components/RelativeTime/text.json, lib/js/app/queryCreator/components/RelativeTimeLabel/RelativeTimeLabel.test.tsx, lib/js/app/queryCreator/components/RelativeTimeLabel/RelativeTimeLabel.tsx, lib/js/app/queryCreator/components/RelativeTimeLabel/text.json, lib/js/app/queryCreator/components/TimePeriod/TimePeriod.tsx, lib/js/app/queryCreator/components/TimePeriod/constants.ts, lib/js/app/queryCreator/components/Timeframe/utils/convertRelativeTime.ts, lib/js/app/queryCreator/constants.ts, lib/js/app/queryCreator/utils/getInterval.test.ts, lib/js/app/queryCreator/utils/getInterval.ts, lib/js/app/queryCreator/utils/index.ts
https://metakeen.atlassian.net/browse/FEE-147
=> feat: 🎸 add support for relative intervals in labels

lib/js/app/queryCreator/components/RelativeTimeLabel/RelativeTimeLabel.test.tsx, lib/js/app/queryCreator/components/RelativeTimeLabel/text.json, lib/js/app/queryCreator/constants.ts
https://metakeen.atlassian.net/browse/FEE-160
=> fix: 🐛 relative time list and typos

lib/js/app/components/EditorVisualization/EditorVisualization.styles.ts, lib/js/app/components/QueryVisualization/QueryVisualization.styles.ts, package.json, yarn.lock
https://metakeen.atlassian.net/browse/FEE-158
=> fix: 🐛 table in edit mode

package.json, yarn.lock
* https://metakeen.atlassian.net/browse/FEE-162
* https://metakeen.atlassian.net/browse/FEE-166
=> chore: 🤖 update ui-core

lib/js/app/components/BrowserPreview/BrowserPreview.styles.ts
https://metakeen.atlassian.net/browse/FEE-175
=> fix: 🐛 headers alignment

lib/js/app/components/ActionsMenu/ActionsMenu.tsx, lib/js/app/components/BrowserQueryMenu/BrowserQueryMenu.styles.ts, lib/js/app/components/BrowserQueryMenu/BrowserQueryMenu.tsx, lib/js/app/components/BrowserQueryMenu/text.json, lib/js/app/components/CacheQuery/CacheQuery.tsx, lib/js/app/components/CacheRefreshRate/CacheRefreshRate.tsx, lib/js/app/components/EditorNavigation/EditorNavigation.styles.ts, lib/js/app/components/EditorNavigation/EditorNavigation.tsx, lib/js/app/components/EditorNavigation/text.json, lib/js/app/constants.ts, lib/js/app/queryCreator/components/Extraction/Extraction.tsx, lib/js/app/queryCreator/components/OrderBy/OrderBy.tsx, lib/js/app/queryCreator/constants.ts
https://metakeen.atlassian.net/browse/FEE-185
=> feat: 🎸 add missing tooltips to ActionsMenu

lib/js/app/components/Browser/Browser.styles.ts, lib/js/app/components/Browser/Browser.tsx
https://metakeen.atlassian.net/browse/FEE-190
=> fix: 🐛 remove flickering from QueryList

lib/js/app/queryCreator/components/Extraction/Extraction.styles.ts, lib/js/app/queryCreator/components/Extraction/Extraction.tsx, lib/js/app/queryCreator/components/Extraction/components/ExtractionProperties/text.json, lib/js/app/queryCreator/components/Extraction/components/ExtractionTitle/ExtractionTitle.test.tsx, lib/js/app/queryCreator/components/Extraction/components/ExtractionTitle/ExtractionTitle.tsx, lib/js/app/queryCreator/components/Extraction/components/ExtractionTitle/text.json, lib/js/app/queryCreator/components/Extraction/constants.ts, lib/js/app/queryCreator/components/Extraction/text.json, public/locales/en/translation.json
https://metakeen.atlassian.net/browse/FEE-200
=> chore: 🤖 update tooltip for extraction

package.json, yarn.lock
https://metakeen.atlassian.net/browse/FEE-187
=> fix: 🐛 prevent view reset on ESC

lib/js/app/queryCreator/components/OrderBy/OrderBy.tsx, lib/js/app/queryCreator/components/OrderBy/components/DirectionList/DirectionList.tsx, lib/js/app/queryCreator/components/OrderBy/components/OrderByProperty/OrderByProperty.test.tsx, lib/js/app/queryCreator/components/OrderBy/constants.ts
https://metakeen.atlassian.net/browse/FEE-197
=> fix: 🐛 set default for <OrderBy/>

lib/js/app/queryCreator/components/QueryArguments/QueryArguments.tsx
https://metakeen.atlassian.net/browse/FEE-203
=> chore: 🤖 set percentile order

lib/js/app/components/AutorunQuery/AutorunQuery.tsx, lib/js/app/components/BrowserQueryMenu/BrowserQueryMenu.tsx, lib/js/app/components/EditorNavigation/EditorNavigation.tsx, lib/js/app/components/TooltipContent/TooltipContent.tsx
https://metakeen.atlassian.net/browse/FEE-258
=> fix: 🐛 enable text wrap for AutorunQuery tooltip

package.json, yarn.lock
https://metakeen.atlassian.net/browse/FEE-256
=> fix: 🐛 checkbox tick

lib/js/app/components/CacheQuery/CacheQuery.styles.ts, lib/js/app/components/CacheQuery/CacheQuery.tsx, lib/js/app/components/QuerySettings/QuerySettings.styles.ts, package.json, yarn.lock
- https://metakeen.atlassian.net/browse/FEE-256
- https://metakeen.atlassian.net/browse/FEE-270
=> style: 💄 reset styles from keen-web

lib/js/app/components/CacheQuery/components/LimitTooltip/LimitTooltip.tsx
https://metakeen.atlassian.net/browse/FEE-273
=> fix: 🐛 cache query tooltip

src/components/CacheQuery/components/LimitTooltip/LimitTooltip.styles.tsx
https://metakeen.atlassian.net/browse/FEE-283
=> style: 💄 set color for LimitTooltip link hover state

public/locales/en/translation.json
align translations related to https://metakeen.atlassian.net/browse/FEE-284
=> chore: 🤖 align translations with query-creator

public/locales/en/translation.json, src/components/Confirm/Confirm.styles.ts, src/components/Confirm/Confirm.test.tsx, src/components/Confirm/Confirm.tsx
https://metakeen.atlassian.net/browse/FEE-291
=> chore: 🤖 update Delete modal with query name

public/locales/en/translation.json, src/components/BrowserQueryMenu/BrowserQueryMenu.styles.ts, src/components/BrowserQueryMenu/BrowserQueryMenu.test.tsx, src/components/BrowserQueryMenu/BrowserQueryMenu.tsx
https://metakeen.atlassian.net/browse/FEE-301
=> chore: 🤖 remove Delete btn from BrowserQueryMenu

src/components/Browser/Browser.styles.ts, src/components/BrowserPreview/BrowserPreview.styles.ts, src/components/BrowserPreview/BrowserPreview.tsx, src/components/Confirm/Confirm.styles.ts, src/components/EditorNavigation/EditorNavigation.styles.ts, src/components/EditorNavigation/EditorNavigation.tsx, src/components/QueriesListItem/QueriesListItem.tsx, src/components/QueriesListItem/QueryListItem.styles.ts
https://metakeen.atlassian.net/browse/FEE-293
=> chore: 🤖 handle long query names

src/components/QueryTagManager/QueryTagManager.tsx
https://metakeen.atlassian.net/browse/FEE-317
=> refactor: 💡 Query Tag Manager

public/locales/en/translation.json
https://metakeen.atlassian.net/browse/FEE-330
=> chore: 🤖 update SaveQuery button label

src/components/QueryTagManager/QueryTagManager.test.tsx, src/components/QueryTagManager/QueryTagManager.tsx
https://metakeen.atlassian.net/browse/FEE-372
=> fix: 🐛 add new tag that is a part of one of other tags

yarn.lock
Upgraded query creator package to version with draggable fields
Closes: #FEE-359
=> feat: 🎸 Query creator package upgraded

public/locales/en/translation.json, src/components/ActionsMenu/ActionsMenu.test.tsx, src/components/ActionsMenu/ActionsMenu.tsx, src/components/BrowserQueryMenu/BrowserQueryMenu.tsx, src/modules/app/saga.test.ts
Closes: 
[#FEE-348](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-348)
=> feat: 🎸 New query option added to actions menu

public/locales/en/translation.json, src/modules/app/saga.test.ts, src/modules/queries/saga.test.ts, src/modules/queries/saga.ts, src/modules/savedQuery/saga.test.ts
Closes: [#FEE-382](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-382)
=> fix: 🐛 Extraction to email - two notifications presented fix

src/components/EditorNavigation/EditorNavigation.tsx, src/components/QueriesListItem/QueriesListItem.tsx, yarn.lock
[#FEE-103](https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-103)
=> feat: 🎸 Added truncate property to badges

yarn.lock
update dataviz and query-creator for
* https://metakeen.atlassian.net/browse/FEE-363
* https://metakeen.atlassian.net/browse/FEE-435
=> chore: 🤖 update keen.io/[dataviz, query-creator]

yarn.lock
https://metakeen.atlassian.net/browse/FEE-480
=> chore: 🤖 bump @keen.io/dataviz

public/locales/en/translation.json, yarn.lock
https://metakeen.atlassian.net/browse/FEE-485
=> feat: 🎸 bump query-creator to show presentation timezone label

package-lock.json, public/index.html, src/KeenExplorer.tsx, src/components/Creator/Creator.tsx, src/contexts/AppContext.ts, src/types.ts
Closes: FEE-513
https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-483
=> feat: 🎸 Proxy timezone settings to query-creator

src/KeenExplorer.tsx, src/constants.ts
Closes: [FEE-552](https://metakeen.atlassian.net/browse/FEE-552)
=> fix: 🐛 Default timezone added

yarn.lock
https://metakeen.atlassian.net/browse/FEE-560
=> chore: 🤖 bump Query Creator

src/components/FilterQueries/FilterQueries.styles.ts, src/components/FilterQueries/FilterQueries.tsx, src/components/FilterQueries/components/FilterItem/FilterItem.styles.ts, src/components/FilterQueries/components/FilterItem/FilterItem.tsx, src/components/FilterQueries/components/SearchTags/SearchTags.styles.ts, src/components/FilterQueries/components/SearchTags/SearchTags.tsx
https://metakeen.atlassian.net/browse/FEE-570
=> fix: 🐛 use keen.io/typography in FilterQueries

src/components/CacheQuery/CacheQuery.styles.ts, src/components/CacheQuery/CacheQuery.tsx, src/components/CacheRefreshRate/CacheRefreshRate.styles.ts, src/components/CacheRefreshRate/CacheRefreshRate.tsx, src/components/QuerySettings/QuerySettings.styles.ts, yarn.lock
part of a fix for https://metakeen.atlassian.net/browse/FEE-569
we need to increase specificity for Data Explorer, I'll handle this in separate PR
=> fix: 🐛 update layout for QuerySettings

src/components/Editor/Editor.styles.ts, src/components/Editor/Editor.tsx, yarn.lock
https://metakeen.atlassian.net/browse/FEE-582
need to bump
* `keen.io/query-creator`
* `keen.io/widget-customization`
=> style: 💄 add responsive styles for Query Creator

yarn.lock
fix/FEE-586-widget-connections
=> chore: 🤖 bump ui-core to handle PropertiesTree line-height

yarn.lock
https://metakeen.atlassian.net/browse/FEE-550
=> chore: 🤖 bump QC for FEE-550

yarn.lock
https://metakeen.atlassian.net/browse/FEE-605
=> chore: 🤖 bump keen dependencies

public/locales/en/translation.json
https://metakeen.atlassian.net/browse/FEE-550
=> chore: 🤖 add missing translations

src/components/BrowserPreview/components/NoPropertiesOnEventStream/NoPropertiesOnEventStream.styles.ts, src/components/BrowserPreview/components/NoPropertiesOnEventStream/NoPropertiesOnEventStream.tsx
update typography for https://metakeen.atlassian.net/browse/FEE-597
=> fix: 🐛 use keen.io/typography

src/components/BrowserPreview/components/NoPropertiesOnEventStream/NoPropertiesOnEventStream.styles.ts, src/components/BrowserPreview/components/NoPropertiesOnEventStream/NoPropertiesOnEventStream.tsx
https://metakeen.atlassian.net/browse/FEE-597
=> style: 💄 rewrite Title with keen.io/typography

yarn.lock
BREAKING CHANGE: legacy build not supported
=> feat: 🎸 update dependencies

src/components/Browser/Browser.test.tsx, src/components/Browser/Browser.tsx, src/components/Browser/constants.ts, src/components/QueriesList/QueriesList.tsx, src/components/QueriesList/index.ts, src/components/QueriesList/types.ts, src/modules/app/actions.ts, src/modules/app/constants.ts, src/modules/app/index.ts, src/modules/app/reducer.test.ts, src/modules/app/reducer.ts, src/modules/app/selectors.ts, src/modules/app/types.ts
https://metakeen.atlassian.net/browse/FEE-349
=> feat: 🎸 persist filters and sort settings

public/locales/en/translation.json
https://metakeen.atlassian.net/browse/FEE-777
=> chore: 🤖 update text copies

jest.config.js, public/locales/en/translation.json, src/components/ActionsMenu/ActionsMenu.tsx, src/components/BrowserQueryMenu/BrowserQueryMenu.test.tsx, src/components/BrowserQueryMenu/BrowserQueryMenu.tsx, src/components/QuerySummary/QuerySummary.styles.ts, src/components/QuerySummary/QuerySummary.test.tsx, src/components/QuerySummary/QuerySummary.tsx, src/components/QuerySummary/__snapshots__/QuerySummary.test.tsx.snap, src/components/QuerySummary/components/Analyses/Analyses.test.tsx, src/components/QuerySummary/components/Analyses/Analyses.tsx, src/components/QuerySummary/components/Analyses/index.ts, src/components/QuerySummary/components/index.ts, src/components/QuerySummary/utils/index.ts, src/components/QuerySummary/utils/transformName.test.ts, src/components/QuerySummary/utils/transformName.ts, yarn.lock
https://metakeen.atlassian.net/browse/FEE-341
=> feat: 🎸 multi-analysis support

src/components/Editor/Editor.tsx
https://metakeen.atlassian.net/browse/FEE-838
=> fix: 🐛 table chart edit mode

src/components/QueriesListItem/QueriesListItem.tsx, src/components/QueriesListItem/QueryListItem.styles.ts
https://metakeen.atlassian.net/browse/FEE-844
=> style: 💄 improve saved queries list UI

package.json, yarn.lock
https://metakeen.atlassian.net/browse/FEE-839
=> chore: 🤖 bump widget customization

package.json, public/locales/en/translation.json, yarn.lock
https://metakeen.atlassian.net/browse/FEE-600
=> fix: 🐛 empty target value for Gauge

package.json, yarn.lock
https://metakeen.atlassian.net/browse/FEE-871
=> chore: 🤖 bump widget-customization

src/components/Editor/Editor.tsx, src/modules/editor/saga.ts
https://metakeen.atlassian.net/jira/software/projects/FEE/boards/10?selectedIssue=FEE-892
=> fix: 🐛 Run query fix

src/components/EditorNavigation/EditorNavigation.styles.ts, src/components/EditorNavigation/EditorNavigation.tsx
https://metakeen.atlassian.net/browse/FEE-104
=> style: 💄 handle long labels

src/components/EditorNavigation/EditorNavigation.styles.ts, src/components/EditorNavigation/EditorNavigation.tsx
https://user-images.githubusercontent.com/23423731/171375670-14d88a6e-fc70-4866-9f68-43676c5cabe7.mov
=> style: 💄 update EditorNavigation

package.json, yarn.lock
https://metakeen.atlassian.net/browse/FEE-908
=> chore: 🤖 bump widget picker
