keen/explorer

- index.html
-Updates copy in navigation bar and call to action buttons
-Adds "close" button to Explorer Demo (when a user clicks this button, the demo closes and they return to the landing page)
-Open `index.html` in your browser to see the proposed changes
-Click the `Take it for a test drive!` button inside the blue header banner to enter the Explorer Demo
-Test the close demo buttons by clicking on both `close` and `x` 
When you click this button:
You should return to this view:
> Updated button text and added ability to close demo

- README.md
- gulpfile.js
Thanks for open-sourcing this project, we use Keen at ft.com to power some of our [product dashboards](https://github.com/Financial-Times/next-beacon-dashboard).
Allows people who have _other things_ running on 8081 to specify an alternate port to run the app on.
`export PORT=5001; gulp;` & `curl -i localhost:5001`
> Run the application on any local port

- client/js/app/components/common/relative_picker.js
This PR, fixes #7, small plural wording in the description text of relative time frame changer. 
relative_picker.js line 39 and 41
go to relative time frame changer UI, and type 1 and 2 in the time amount input,  see the difference it makes. Or see the gif below
http://g.recordit.co/Lme5HMhBjk.gif
Note: gulp test:unit is passing but I could not run gulp test:functional because raises following error:
"ReferenceError: mochaSelenium is not defined..."
> Correct plural suffix when changing relative time amount

- index.html
Sets the default query view for `Visit Duration` to a pie chart.
> Visit Duration now defaults to pie chart

- README.md
Fixed the Persistence documentation link that was 404ing, now a relative link
Look at the README.md at the bottom of this section: https://github.com/keen/explorer#3-optionally-include-persistence
See above and click
> Fixed persistence docs link

- client/js/app/stores/ExplorerStore.js
- test/unit/stores/ExplorerStoreSpec.js
@aroc 
This adds the `ExplorerStore` logic for switching to & from funnel analysis types. Properties should flow in and out of the steps property when switching analysis types.
There's also a small refactor to use a set of update preparation functions, rather than making the `_update` function super chaotic.
Well, unfortunately, you can't. There is no functional way to actually touch this code, because we don't actually have a funnel analysis_type yet. I'd suggest reading the tests thoroughly. If those make sense, and pass in CI, then we should be golden.
> Funnel data model

- client/js/app/app.js
- test/unit/app_spec.js
closes #52 
Looks like we had a mistaken `!` before `isEmailExtraction`, which was causing trouble. I removed that, and we're good to go.
I also set a sort of foundation for testing `App`.
> run queries automatically on pageload

- client/js/app/actions/ExplorerActions.js
- client/js/app/components/explorer/visualization/chart.js
- client/js/app/components/explorer/visualization/data_table.js
- client/js/app/components/explorer/visualization/index.js
- client/js/app/components/explorer/visualization/keen_viz.js
- client/js/app/stores/ExplorerStore.js
- client/js/app/utils/ExplorerUtils.js
- test/support/TestHelpers.js
- test/unit/actions/ExplorerActionsSpec.js
- test/unit/components/explorer/visualization/chart_spec.js
- test/unit/stores/ExplorerStoreSpec.js
This fixes the issue where we couldn't visualize funnel query responses. Keen.js requires the entire response in order to properly auto-visualize a Funnel query. Rather than just storing the result of a query in the model (ExplorerStore models), we're instead storing the entire response.
> Funnels UI:  Funnel visualization support

- client/js/app/components/explorer/visualization/index.js
- test/unit/components/explorer/visualization/index_spec.js
Sets a default chart type if a saved query doesn't have a `chart_type` set. The default chart type is the first item returned from `ExplorerUtils.getChartTypeOptions`.
* `client/js/app/components/explorer/visualization/index.js#43`
```js
client = new Keen({
projectId: "5011efa95f546f2ce2000000",
readKey: "ef717eaec4aeb8e8b8b18891ffaa1eafed8c14cac1f7cb90030eaa7ed79ed2d540ee267547267c73f4c6e7ff9bcb8f7dec4df9500499a70737777d71971a20e6e3cd6532b44a44c5d269811178c2308867fd5082d44e51c05496b0099c4a06649207b8db43fe0458cf3cc059f5ecaadc",
masterKey: "project master key here",
protocol: "https",
host: "api.keen.io/3.0",
requestType: "xhr"
});
```
> Set a default visualization for saved queries without a chart type

- package.json
This removes the warning "keen-explorer 2.0.0: No repository field"
Run `npm install`. The warning message should not be at the end of the output.
> Add 'repository' field to package.json

- client/js/app/components/explorer/query_actions.js
Corrects some copy in the Explorer that shows when doing an extraction. Keen IO API now supports saved queries. 
Visually check that the copy is now accurate. Try to do an extraction with the "Bulk CSV extraction by email" radio button to see where it appears in the Explorer. 
Couldn't find any
> Removed old copy

- client/js/app/components/explorer/visualization/keen_viz.js
Resolves issue causing funnel steps to appear out of order in some visualizations. 
Get the Explorer running locally and try running several funnel analyses. Ensure that the order of the steps in your charts matches the order of the steps in your query.
> Ensure steps appear in correct order on funnel visualizations

- client/js/app/app.js
- client/js/app/utils/ExplorerUtils.js
- test/support/TestHelpers.js
The goal of this PR is to remove the `host` property from the embeddable code sample without making any changes to the client. This is an update to https://github.com/keen/explorer/pull/170.
> Fix Issue #167

- package.json
It updates explorer to use the latest version of keen-dataviz.js, which is `v1.0.4`.
> Use latest keen-dataviz.js

- client/js/app/utils/ExplorerUtils.js
Resolves https://github.com/keen/explorer/issues/150. The embeddable code sample for percentile queries now includes the percentile property and value. 
**Note:** The percentile value is currently being saved and executed as a string (https://github.com/keen/explorer/issues/168) instead of a number. Planning to fix that issue and roll the changes out together to prevent additional confusion for folks copy/pasting the code sample.
> Fix issue #150

- client/js/app/app.js
I don't see a need to expose the React when loading the explorer.
I assume that this was done initially to make it possible to use the React DevTools, but the integration between React and its DevTools was changed in React 0.12 to avoid requiring to have React as a global (instead, the DevTools are exposing a global variable)
> Avoid overwriting the React global variable

- client/js/app/validations/ExplorerValidations.js
- dist/keen-explorer.css
- test/unit/validations/ExplorerValidationsSpec.js
It's currently possible for a user to run a percentile query without a percentile value (a required field). This results in an error and the query appearing to load indefinitely. This PR addresses that issue by adding validation to notify users when the percentile value is missing.
- Run a percentile query with no percentile value and confirm that an error is displayed in the UI. 
- Run a percentile query with a percentile value and confirm that it executes as expected.
- Confirm all tests pass.
> Add percentile value validation

- client/js/app/components/explorer/index.js
- client/js/app/components/explorer/query_actions.js
- client/js/app/components/explorer/visualization/index.js
- client/js/app/components/explorer/visualization/keen_viz_config.js
- client/js/app/stores/AppStateStore.js
- dist/keen-explorer.css
- test/unit/components/explorer/query_actions_spec.js
- test/unit/components/explorer/visualization/keen_viz_config_spec.js
This PR gives users the ability to show and hide the dataviz config component. It is a starting point that does not include styling. 
- Get the project running locally and click on the "Customize" button. 
- You should see a "Hello, World" placeholder notice appear. 
- Confirm that you can close the notice by clicking on the "Customize" button or the "x".
> Toggle dataviz config component

- client/js/app/stores/ExplorerStore.js
- test/unit/stores/ExplorerStoreSpec.js
The `interval` parameter is not supported by [funnels](https://keen.io/docs/api/#funnels). This PR removes the invalid `interval` parameter from the Explorer model for this type of query. 
This change resolves the issue saving funnel queries reported in #121. The changes in this PR do not address the issue of toggling the Interval component to a "closed" state when the query builder is cleared out (also reported in #121); I recommend addressing those in a separate PR.
I added a unit test for this change. To test these changes in the browser, create a funnel query and confirm that there is no `interval` set in the URL.
> Remove invalid interval parameter from funnel queries

- client/js/app/actions/ExplorerActions.js
- client/js/app/components/explorer/index.js
- client/js/app/components/explorer/query_actions.js
- client/js/app/constants/ExplorerConstants.js
- client/js/app/stores/ExplorerStore.js
- test/unit/actions/ExplorerActionsSpec.js
- test/unit/components/explorer/index_spec.js
- test/unit/components/explorer/query_actions_spec.js
- test/unit/stores/ExplorerStoreSpec.js
This PR builds off of https://github.com/keen/explorer/pull/180, a PR created by @menismu, which offers users the ability to clone saved queries. This feature was requested in https://github.com/keen/explorer/issues/151. Many thanks to @menismu for implementing this feature!
The updates in this PR include:
- Makes the clone button white.
- A small update to the clone success message copy.
- Uses `_.cloneDeep` to ensure the source query and newly cloned query reference different objects.
- Clones `metadata.visualization.chart_type` to ensure that cloned queries have the original query visualization type set as default. This also resolves an issue where cloned queries were inconsistently displaying the error "A chart type is required. Check out the .type() method." in the UI.
- Adds some …
> Clone saved query feature

- client/js/app/actions/ExplorerActions.js
- client/js/app/components/explorer/index.js
- client/js/app/components/explorer/query_actions.js
- client/js/app/constants/ExplorerConstants.js
- client/js/app/stores/ExplorerStore.js
- test/unit/actions/ExplorerActionsSpec.js
- test/unit/components/explorer/index_spec.js
- test/unit/components/explorer/query_actions_spec.js
- test/unit/stores/ExplorerStoreSpec.js
It implements a Clone function for saved queries, the user is able to clone a saved query to later apply some changes and save the cloned query as a new query.
Thinking in UAT this should be tested, first creating or saving a query and after that use the Clone button to make a clone of the saved query and check the cloned query can be modified before create a new one.
Also, it is important to mention tests have been created following the same guidelines I´ve seen in the code, most important files modified are ExplorerActions.js and ExplorerStore.js from my point of view but also query_actions.js and index.js in components/explorer path.
In terms of Development, I´ve tried to be as less intrusive as possible and also I made some assumptions like only the query attributes of a saved query …
> Implemented the clone function:

- client/js/app/stores/ExplorerStore.js
- package.json
- test/unit/stores/ExplorerStoreSpec.js
Saved queries will represent `group_by` as a `null` for queries without a group_by value. Explorer tries to be smart by turning non-array `group_by` values into single-element arrays, but makes the poor mistake of wrapping `null` `group_by`s into an array. That messes things up down the line, specifically causing Explorer to think the query is categorial (has a group_by).
This change removes `null` values from the `group_by` array. Effectively, for users, that means they will get the correct chart type options for their `singular` saved queries.
Pull it down, and create a regular ol' count query with a metric type. Save it. The chart type should still be metric. If it's not we have trouble.
I'd also suggest trying a few other query types, just to watch for unintended consequences.
Step …
> remove null values when we turn the group_by into an array

- client/js/app/components/common/datepicker.js
- client/js/app/components/common/event_browser.js
- client/js/app/components/common/filter_value_fields.js
- client/js/app/components/common/geo.js
- client/js/app/components/common/input.js
- client/js/app/components/common/react_select.js
- client/js/app/components/common/relative_picker.js
- dist/keen-explorer.js
This PR disables browser autocomplete for all `<input type="text">` fields.
Here's a screenshot of the issue being addressed:
https://github.com/keen/explorer/issues/158
> Disable native autocomplete for all input fields

- client/js/app/stores/ExplorerStore.js
- client/js/app/utils/DateUtils.js
- client/js/app/utils/FormatUtils.js
- client/js/app/utils/ProjectUtils.js
- dist/keen-explorer.js
- test/unit/stores/ExplorerStoreSpec.js
This PR adds logic to find the first timezone value matching the user's local timezone offset. This also corrects for DST, shifting the offset ahead an hour when necessary to ensure the proper match.
Load it up and take it for a spin.
This will resolve a persistent issue where charts appear to be "wrong" for users in the US. This happens when timestamps are localized, making days and months display one whole unit earlier than what is expected. Eg: March 1st (midnight) displays as February 28th (-7hr). By setting the proper timezone, the results are shifted in the other direction.
> Find and set local timezone by default

- client/js/app/components/explorer/query_builder/funnels/funnel_step.js
- client/js/app/components/explorer/visualization/chart.js
- client/js/app/stores/ExplorerStore.js
- client/js/app/utils/FunnelUtils.js
- client/js/app/validations/StepValidations.js
- dist/keen-explorer.js
- test/support/TestHelpers.js
- test/unit/stores/ExplorerStoreSpec.js
- test/unit/utils/FunnelUtilsSpec.js
- test/unit/validations/StepValidationsSpec.js
This adds a 'With Actors' property for funnel steps. This also changes the explorer so it displays the _whole_ response in the "JSON" visualization so we can view said actors.
> Add 'with_actors' checkbox for funnel queries

- lib/js/app/components/explorer/GroupBy.js
https://github.com/keen/keen/issues/48
> fix: 🐛 optional order field cannot be empty string

- lib/js/app/queryCreator/modules/events/actions.ts
- lib/js/app/queryCreator/modules/events/constants.ts
- lib/js/app/queryCreator/modules/events/index.ts
- lib/js/app/queryCreator/modules/events/reducer.ts
- lib/js/app/queryCreator/modules/events/types.ts
- lib/js/app/queryCreator/saga.ts
- Compute schema tree async to do not block user interface rendering.
- Remove obsolete request for schema before filters transformation.
> Refactor Schema Serialize

- lib/js/app/queryCreator/components/EventCollection/EventCollection.test.tsx
- lib/js/app/queryCreator/components/EventCollection/EventCollection.tsx
Related with JIRA FEE-193 ticket.
> fix: 🐛 prevent reset query after selecting same event stream

- src/components/QuerySummary/components/FunnelStep/FunnelStep.tsx
https://metakeen.atlassian.net/browse/FEE-559
> fix: 🐛 add styling to Query Summary filters
